<a href="https://colab.research.google.com/github/krishrocks11/Learning/blob/main/NN%20Assignment%202/Fuzzy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U scikit-fuzzy

In [ ]:
import numpy as np
import math
x = [[0.1, 0.7, 0.2, 0.0],[0.0, 0.5, 0.5, 0.0],[0.2, 0.2, 0.2, 0.4],[0.8, 0.1, 0.0, 0.1],[0.3, 0.0, 0.4, 0.3],[0.0, 0.4, 0.0, 0.6],[0.5, 0.0, 0.4, 0.1],[0.6, 0.3, 0.0, 0.1],[0.0, 0.5, 0.1, 0.4],[0.1, 0.6, 0.0, 0.3],[0.3, 0.2, 0.1, 0.4],[0.1, 0.5, 0.4, 0.0],[0.2, 0.0, 0.2, 0.6],[0.2, 0.6, 0.1, 0.1],[0.1, 0.7, 0.1, 0.1],[0.2, 0.4, 0.2, 0.2]]
R = np.zeros([16,16])
R_prime = np.zeros([16,16])
R_prime_1 = np.zeros([16,16])
R_prime_2 = np.zeros([16,16])
R_prime_3 = np.zeros([16,16])
R_prime_4 = np.zeros([16,16])
R_alpha_4 = np.zeros([16,16])
R_alpha_6 = np.zeros([16,16])
R_alpha_8 = np.zeros([16,16])
dot = 0
mag_i = 0
mag_j = 0
for i in range(16):
  for j in range(16):
    for k in range(4):
      dot += x[i][k]*x[j][k]
      mag_i += x[i][k]*x[i][k]
      mag_j += x[j][k]*x[j][k]
    R[i][j] = abs(dot)/(math.sqrt(mag_i*mag_j))
    dot = 0
    mag_i = 0
    mag_j = 0




In [ ]:
R

array([[1.        , 0.8660254 , 0.5143445 , 0.25125945, 0.25671802,
        0.52839595, 0.27297434, 0.54173634, 0.77692697, 0.86276528,
        0.4720588 , 0.92391316, 0.12309149, 0.96590921, 0.98130676,
        0.87438565],
       [0.8660254 , 1.        , 0.53452248, 0.08703883, 0.48507125,
        0.39223227, 0.43643578, 0.31277162, 0.65465367, 0.62554324,
        0.38729833, 0.98198051, 0.21320072, 0.76376262, 0.78446454,
        0.80178373],
       [0.5143445 , 0.53452248, 1.        , 0.51176632, 0.84266484,
        0.83862787, 0.64153303, 0.61300603, 0.81649658, 0.72446168,
        0.96609178, 0.58321184, 0.91168461, 0.64153303, 0.57655666,
        0.85714286],
       [0.25125945, 0.08703883, 0.51176632, 1.        , 0.56997045,
        0.17069719, 0.77873061, 0.94374021, 0.17094086, 0.30853045,
        0.67419986, 0.24691458, 0.40824829, 0.43684888, 0.2731155 ,
        0.51176632],
       [0.25671802, 0.48507125, 0.84266484, 0.56997045, 1.        ,
        0.42808634, 0.89973541, 

In [ ]:
import skfuzzy
#R_prime = R
#R_prime[2][4] = R[2][4]
R_prime = skfuzzy.fuzzymath.maxmin_composition(R, R)
#R_prime = skfuzzy.fuzzymath.maxmin_composition(R_prime, R_prime)
#if (R_prime.all() == R.all()):
#  print("budududu")
#else:
#  print("badadadada")
#R_prime == R

In [ ]:
R_prime_1 = skfuzzy.fuzzymath.maxmin_composition(R_prime, R_prime)
R_prime_2 = skfuzzy.fuzzymath.maxmin_composition(R_prime_1, R_prime_1)
R_prime_3 = skfuzzy.fuzzymath.maxmin_composition(R_prime_2, R_prime_2)
#R_prime_2 == R_prime_3

In [ ]:
#R_prime
R_prime_3

array([[1.        , 0.92391316, 0.85714286, 0.77873061, 0.84266484,
        0.94053994, 0.84266484, 0.77873061, 0.94053994, 0.94053994,
        0.85714286, 0.92391316, 0.85714286, 0.98130676, 0.98130676,
        0.93313895],
       [0.92391316, 1.        , 0.85714286, 0.77873061, 0.84266484,
        0.92391316, 0.84266484, 0.77873061, 0.92391316, 0.92391316,
        0.85714286, 0.98198051, 0.85714286, 0.92391316, 0.92391316,
        0.92391316],
       [0.85714286, 0.85714286, 1.        , 0.77873061, 0.84266484,
        0.85714286, 0.84266484, 0.77873061, 0.85714286, 0.85714286,
        0.96609178, 0.85714286, 0.91168461, 0.85714286, 0.85714286,
        0.85714286],
       [0.77873061, 0.77873061, 0.77873061, 1.        , 0.77873061,
        0.77873061, 0.77873061, 0.94374021, 0.77873061, 0.77873061,
        0.77873061, 0.77873061, 0.77873061, 0.77873061, 0.77873061,
        0.77873061],
       [0.84266484, 0.84266484, 0.84266484, 0.77873061, 1.        ,
        0.84266484, 0.89973541, 

In [ ]:
for i in range(16):
  for j in range(16):
    if (R_prime_3[i][j]>=0.4):
      R_alpha_4[i][j] = 1


In [ ]:
R_alpha_4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [ ]:
for i in range(16):
  for j in range(16):
    if (R_prime_3[i][j]>=0.8):
      R_alpha_8[i][j] = 1

In [ ]:
R_alpha_8

array([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,

In [ ]:
for i in range(16):
  for j in range(16):
    if (R_prime_3[i][j]>=0.85):
      R_alpha_6[i][j] = 1

In [ ]:
R_alpha_6

array([[1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,